[package]
name = "git-local-server"
description = "Initialize and serve local Git repositories"
version = "2.3.0"
edition = "2021"
authors = [
    "Guilherme Caldas <gcaldas@chemis.tech>",
]
license = "BSD-2-Clause"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[dependencies]
git2 = { version = "0.20.0", features = ["vendored-libgit2"] }
clap = { version = "4.5.26", features = ["derive", "cargo"] }
dav-server = { version = "0.7.0", features = ["warp-compat"] }
local-ip-address = "0.6.3"
tokio = { version = "1.0", features = ["full"] }
warp = "0.3.7"
openssl = { version = "0.10.70", features = ["vendored"] }
indicatif = "0.17.11"
